### ISSUE TITLE
pattern option does not appear to work as explained.

### ISSUE THREAD

**Issue by ryandagg** [heiseshandian/dynamic-alias-resolve-plugin#2]
The test pattern used across my webpack config is `/\.(js|mjs|jsx|ts|tsx)$/`
This leads to the `dynamic` function never being called.
Using a slight tweak to the example `/\.ts$/` also leads to `dynamic` function never being called.
The repo is full of .ts, .tsx, and .js files.
`/.*/` is the only way I've found so far to get the function passed to `dynamic` getting called.
Tested via a build script with 
```
new DynamicAliasResolvePlugin({
    alias: "lib",
    dynamic: (request, alias) => {
        throw new Error()
    },
    pattern: /.*/,
    // pattern: /\.(js|mjs|jsx|ts|tsx)$/,
})
```

**Comment by heiseshandian** [comment]
Hi, @ryandagg , do you want to replace the path beginning with `lib`? Bellow is the core logic of `DynamicAliasResolvePlugin` plugin, as you can see, we only call `dynamic` function when current module path begins with the alias that you specified(here is `lib`). 
Oh, I see, the reason that your `dynamic` function is never being called is that when we import files in our module, we always ignore the file extension. For instance, when we want to import `{path}/a.js`, we always write `import {something} from {path}/a` instead of `import {something} from {path}/a.js`, which will result in that the pattern that you specified will never be matched.

```js
for (const name of alias) {
  if (innerRequest.startsWith(name)) {
    const dynamicPath = dynamic(request, name);
    if (!dynamicPath) {
      continue;
    }

    const newRequestPath = path.resolve(dynamicPath, innerRequest.substr(name.length + 1));

    if (!fs.existsSync(newRequestPath)) {
      continue;
    }

    const obj = Object.assign({}, request, {
      request: newRequestPath,
    });
    return resolver.doResolve(
      "resolve",
      obj,
      `DynamicAliasResolvePlugin ${newRequestPath}`,
      resolveContext,
      (err, result) => {
        if (err) return callback(err);
        // Don't allow other aliasing or raw request
        if (result === undefined) return callback(null, null);
        return callback(null, result);
      }
    );
  }
}
```
